driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y
      - RUN sudo mkdir -p /data/splunk-test

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y
      - RUN sudo mkdir -p /data/splunk-test

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts
      - RUN sudo mkdir -p /data/splunk-test

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts
      - RUN sudo mkdir -p /data/splunk-test

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts
      - RUN sudo mkdir -p /data/splunk-test

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts
      - RUN sudo mkdir -p /data/splunk-test

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN sudo mkdir -p /data/splunk-test

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN sudo mkdir -p /data/splunk-test

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN sudo mkdir -p /data/splunk-test

suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true

  - name: client-inputs-outputs
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        outputs_conf:
          sslCommonNameToCheck: sslCommonName
          sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
          sslPassword: password
          sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
          sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123

  - name: server-runas-root
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: true
        is_server: true
        accept_license: true
        ssl_options:
          enable_ssl: true

  - name: server-runas-splunk
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        is_server: true
        accept_license: true
        ssl_options:
          enable_ssl: true
        web_port: 8443

  - name: disabled
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      splunk:
        disabled: true

  - name: server_lwrps
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        accept_license: true
        is_server: true

  - name: client_lwrps
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        accept_license: true
        is_server: false
