---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@5.0.3
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
    secrets: inherit

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - amazonlinux-2023
          - debian-11
          - debian-12
          - rockylinux-8
          - rockylinux-9
          - ubuntu-22.04
          - ubuntu-24.04
          - opensuse-leap-15
        suite:
          - "client-inputs-outputs"
          - "client-resources"
          - "client-runas-splunk"
          - "default"
          - "disabled"
          - "server-cluster-master"
          - "server-resources"
          - "server-runas-root"
          - "server-runas-splunk"
          - "server-shcluster-member"
          - "server-shdeployer"
          - "uninstall-forwarder"
          - "upgrade-client"
          - "upgrade-server"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Dokken
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
          set -x
          sudo journalctl -l --since today
          KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"

